on:
  workflow_dispatch:

jobs:
  migrate-database:
    name: Migrate Database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install

      - name: Run Database Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
